"""empty message

Revision ID: 27279fc8b980
Revises: 96d1dd0f2cdc
Create Date: 2020-10-11 22:47:50.278179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27279fc8b980'
down_revision = '96d1dd0f2cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
